import gleeunit/should
import sqlc_gen_gleam/internal/generate

pub fn comment_dont_edit_test() {
  generate.comment_dont_edit()
  |> should.equal(
    "//// Code generated by sqlc_gen_gleam. DO NOT EDIT.\n//// versions:\n////   sqlc_gen_gleam v0.0.1\n////",
  )
}
