//// Code generated by parrot. DO NOT EDIT.
////

import gleam/option.{type Option}
import gleam/dynamic/decode
import gleam/time/timestamp.{type Timestamp}
import parrot/dev

pub type GetUser {
  GetUser(
    id: Int,
    username: String,
    created_at: Option(Timestamp)
  )
}

pub fn get_user(id id: Int){
  let sql = "SELECT
  id, username, created_at
FROM
  users
WHERE
  id = $1
LIMIT
  1"
  #(sql, [dev.ParamInt(id)])
}

pub fn get_user_decoder() -> decode.Decoder(GetUser) {
  use id <- decode.field(0, decode.int)
  use username <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.optional(dev.datetime_decoder()))
  decode.success(GetUser(id: , username: , created_at: ))
}

pub type ListUsers {
  ListUsers(
    id: Int,
    username: String,
    created_at: Option(Timestamp)
  )
}

pub fn list_users(){
  let sql = "SELECT
  id, username, created_at
FROM
  users
ORDER BY
  created_at DESC"
  #(sql, Nil)
}

pub fn list_users_decoder() -> decode.Decoder(ListUsers) {
  use id <- decode.field(0, decode.int)
  use username <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.optional(dev.datetime_decoder()))
  decode.success(ListUsers(id: , username: , created_at: ))
}

pub fn create_user(name name: String){
  let sql = "INSERT INTO
  users (username)
VALUES
  ($1)"
  #(sql, [dev.ParamString(name)])
}

pub fn update_user_username(username username: String, id id: Int){
  let sql = "UPDATE users
SET
  username = $1
WHERE
  id = $2"
  #(sql, [dev.ParamString(username), dev.ParamInt(id)])
}

pub fn delete_user(id id: Int){
  let sql = "DELETE FROM users
WHERE
  id = $1"
  #(sql, [dev.ParamInt(id)])
}

pub type GetUserByUsername {
  GetUserByUsername(
    id: Int,
    username: String,
    created_at: Option(Timestamp)
  )
}

pub fn get_user_by_username(username username: String){
  let sql = "SELECT
  id, username, created_at
FROM
  users
WHERE
  username = $1
LIMIT
  1"
  #(sql, [dev.ParamString(username)])
}

pub fn get_user_by_username_decoder() -> decode.Decoder(GetUserByUsername) {
  use id <- decode.field(0, decode.int)
  use username <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.optional(dev.datetime_decoder()))
  decode.success(GetUserByUsername(id: , username: , created_at: ))
}