//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dict.{type Dict}
import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type CountUsers {
  CountUsers(count: Int)
}

pub fn count_users() {
  let sql =
    "SELECT
  count(*)
FROM
  users"
  #(sql, [], count_users_decoder())
}

pub fn count_users_decoder() -> decode.Decoder(CountUsers) {
  use count <- decode.field(0, decode.int)
  decode.success(CountUsers(count:))
}

pub fn create_user(username username: String) {
  let sql =
    "INSERT INTO
  users (username)
VALUES
  (?)"
  #(sql, [dev.ParamString(username)])
}

pub fn update_user_username(username username: String, id id: Int) {
  let sql =
    "UPDATE users
SET
  username = ?
WHERE
  id = ?"
  #(sql, [dev.ParamString(username), dev.ParamInt(id)])
}

pub type GetUserByUsername {
  GetUserByUsername(
    id: Int,
    username: String,
    created_at: Option(String),
    balance: Float,
    last_known_location: Option(Float),
    avatar: Option(BitArray),
  )
}

pub fn get_user_by_username(username username: String) {
  let sql =
    "SELECT
  id, username, created_at, balance, last_known_location, avatar
FROM
  users
WHERE
  username = ?
LIMIT
  1"
  #(sql, [dev.ParamString(username)], get_user_by_username_decoder())
}

pub fn get_user_by_username_decoder() -> decode.Decoder(GetUserByUsername) {
  use id <- decode.field(0, decode.int)
  use username <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.optional(decode.string))
  use balance <- decode.field(3, decode.float)
  use last_known_location <- decode.field(4, decode.optional(decode.float))
  use avatar <- decode.field(5, decode.optional(decode.bit_array))
  decode.success(GetUserByUsername(
    id:,
    username:,
    created_at:,
    balance:,
    last_known_location:,
    avatar:,
  ))
}
