//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/float
import gleam/list
import gleam/option
import gleam/string
import gleam/time/calendar.{type Date, type TimeOfDay, Date}
import gleam/time/timestamp.{type Timestamp}

pub type Param {
  ParamInt(Int)
  ParamString(String)
  ParamFloat(Float)
  ParamBool(Bool)
  ParamBitArray(BitArray)
  ParamTimestamp(Timestamp)
  ParamDate(Date)
  ParamList(List(Param))
  ParamDynamic(decode.Dynamic)
  ParamNullable(option.Option(Param))
}

pub fn bool_decoder() {
  let int_to_bool = {
    decode.int
    |> decode.then(fn(v) {
      case v {
        0 -> decode.success(False)
        1 -> decode.success(True)
        _ -> decode.failure(False, "could not decode int to boolean")
      }
    })
  }
  decode.one_of(decode.bool, or: [int_to_bool])
}

pub fn datetime_decoder() -> decode.Decoder(Timestamp) {
  decode.one_of(datetime_string_decoder(), or: [
    datetime_tuple_decoder(),
    timestamp_decoder(),
  ])
}

/// https://github.com/lpil/pog/blob/v4.1.0/src/pog.gleam#L394
fn timestamp_decoder() -> decode.Decoder(Timestamp) {
  use microseconds <- decode.map(decode.int)
  let seconds = microseconds / 1_000_000
  let nanoseconds = { microseconds % 1_000_000 } * 1000
  timestamp.from_unix_seconds_and_nanoseconds(seconds, nanoseconds)
}

/// https://github.com/lpil/pog/blob/v4.1.0/src/pog.gleam#L873
pub fn calendar_date_decoder() -> decode.Decoder(Date) {
  use year <- decode.field(0, decode.int)
  use month <- decode.field(1, decode.int)
  use day <- decode.field(2, decode.int)
  case calendar.month_from_int(month) {
    Ok(month) -> decode.success(calendar.Date(year:, month:, day:))
    Error(_) ->
      decode.failure(calendar.Date(0, calendar.January, 1), "Calendar date")
  }
}

fn datetime_string_decoder() -> decode.Decoder(Timestamp) {
  decode.string
  |> decode.then(fn(datetime_str) {
    case timestamp.parse_rfc3339(datetime_str) {
      Ok(ts) -> decode.success(ts)
      Error(_) ->
        decode.failure(
          timestamp.from_unix_seconds(0),
          "Invalid datetime format",
        )
    }
  })
}

fn datetime_tuple_decoder() -> decode.Decoder(Timestamp) {
  use date <- decode.field(0, date_decoder())
  use time <- decode.field(1, time_decoder())

  timestamp.from_calendar(date:, time:, offset: calendar.utc_offset)
  |> decode.success()
}

fn date_decoder() -> decode.Decoder(Date) {
  use year <- decode.field(0, decode.int)
  use month <- decode.field(
    1,
    decode.int
      |> decode.then(fn(month) {
        case calendar.month_from_int(month) {
          Error(_) -> decode.failure(calendar.January, "Month")
          Ok(month) -> decode.success(month)
        }
      }),
  )
  use day <- decode.field(2, decode.int)

  decode.success(Date(year:, month:, day:))
}

fn time_decoder() -> decode.Decoder(TimeOfDay) {
  use hours <- decode.field(0, decode.int)
  use minutes <- decode.field(1, decode.int)
  use #(seconds, nanoseconds) <- decode.field(2, seconds_decoder())

  calendar.TimeOfDay(hours:, minutes:, seconds:, nanoseconds:)
  |> decode.success()
}

fn seconds_decoder() -> decode.Decoder(#(Int, Int)) {
  let int = {
    decode.int
    |> decode.map(fn(i) { #(i, 0) })
  }
  let float = {
    decode.float
    |> decode.map(fn(f) {
      let floored = float.floor(f)
      let seconds = float.round(floored)
      let nanoseconds = float.round({ f -. floored } *. 1_000_000_000.0)
      #(seconds, nanoseconds)
    })
  }
  decode.one_of(int, [float])
}

pub type Simple {
  Simple(col_0: Int)
}

pub fn simple() {
  let sql = "select 1"
  #(sql, [], simple_decoder())
}

pub fn simple_decoder() -> decode.Decoder(Simple) {
  use col_0 <- decode.field(0, decode.int)
  decode.success(Simple(col_0:))
}

pub type CountUsers {
  CountUsers(count: Int)
}

pub fn count_users() {
  let sql =
    "SELECT
  count(*)
FROM
  users"
  #(sql, [], count_users_decoder())
}

pub fn count_users_decoder() -> decode.Decoder(CountUsers) {
  use count <- decode.field(0, decode.int)
  decode.success(CountUsers(count:))
}

pub fn create_user(username username: String) {
  let sql =
    "INSERT INTO
  users (username)
VALUES
  (?)"
  #(sql, [ParamString(username)])
}

pub fn create_user_with_role(
  username username: String,
  role role: option.Option(String),
) {
  let sql =
    "INSERT INTO
  users (username, role)
VALUES
  (?, ?)"
  #(sql, [
    ParamString(username),
    ParamNullable(option.map(role, fn(v) { ParamString(v) })),
  ])
}

pub fn update_user_username(username username: String, id id: Int) {
  let sql =
    "UPDATE users
SET
  username = ?
WHERE
  id = ?"
  #(sql, [ParamString(username), ParamInt(id)])
}

pub fn update_user_type(type_ type_: option.Option(String), id id: Int) {
  let sql =
    "UPDATE users
SET
  type = ?
WHERE
  id = ?"
  #(sql, [
    ParamNullable(option.map(type_, fn(v) { ParamString(v) })),
    ParamInt(id),
  ])
}

pub type GetUserByUsername {
  GetUserByUsername(
    id: Int,
    username: String,
    created_at: option.Option(String),
    balance: Float,
    last_known_location: option.Option(Float),
    role: option.Option(String),
    avatar: option.Option(BitArray),
    type_: option.Option(String),
  )
}

pub fn get_user_by_username(username username: String) {
  let sql =
    "SELECT
  id, username, created_at, balance, last_known_location, role, avatar, type
FROM
  users
WHERE
  username = ?
LIMIT
  1"
  #(sql, [ParamString(username)], get_user_by_username_decoder())
}

pub fn get_user_by_username_decoder() -> decode.Decoder(GetUserByUsername) {
  use id <- decode.field(0, decode.int)
  use username <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.optional(decode.string))
  use balance <- decode.field(3, decode.float)
  use last_known_location <- decode.field(4, decode.optional(decode.float))
  use role <- decode.field(5, decode.optional(decode.string))
  use avatar <- decode.field(6, decode.optional(decode.bit_array))
  use type_ <- decode.field(7, decode.optional(decode.string))
  decode.success(GetUserByUsername(
    id:,
    username:,
    created_at:,
    balance:,
    last_known_location:,
    role:,
    avatar:,
    type_:,
  ))
}

pub type PostsByUsername {
  PostsByUsername(id: Int, title: String, user_id: Int)
}

pub fn posts_by_username(username username: String) {
  let sql =
    "select
  id,
  title,
  user_id
from posts
where user_id = (
  select id
  from users
  where username = ?
)"
  #(sql, [ParamString(username)], posts_by_username_decoder())
}

pub fn posts_by_username_decoder() -> decode.Decoder(PostsByUsername) {
  use id <- decode.field(0, decode.int)
  use title <- decode.field(1, decode.string)
  use user_id <- decode.field(2, decode.int)
  decode.success(PostsByUsername(id:, title:, user_id:))
}

pub type PostsByAdmins {
  PostsByAdmins(id: Int, title: String, user_id: Int)
}

pub fn posts_by_admins() {
  let sql =
    "select
  id,
  title,
  user_id
from posts
where user_id in (
  select id
  from users
  where users.role = 'admin'
)"
  #(sql, [], posts_by_admins_decoder())
}

pub fn posts_by_admins_decoder() -> decode.Decoder(PostsByAdmins) {
  use id <- decode.field(0, decode.int)
  use title <- decode.field(1, decode.string)
  use user_id <- decode.field(2, decode.int)
  decode.success(PostsByAdmins(id:, title:, user_id:))
}

pub type PostWithUser {
  PostWithUser(posts: option.Option(decode.Dynamic), user_id: Int)
}

pub fn post_with_user(id id: Int) {
  let sql =
    "select posts.id, posts.created_at, posts.title, posts.user_id, users.id as user_id
from posts
inner join users on users.id = posts.id
where posts.id = ?
limit 1"
  #(sql, [ParamInt(id)], post_with_user_decoder())
}

pub fn post_with_user_decoder() -> decode.Decoder(PostWithUser) {
  use posts <- decode.field(0, decode.optional(decode.dynamic))
  use user_id <- decode.field(1, decode.int)
  decode.success(PostWithUser(posts:, user_id:))
}

pub type PostsByIds {
  PostsByIds(id: Int)
}

pub fn posts_by_ids(ids ids: List(Int)) {
  let ids_slice = string.repeat(",?", list.length(ids))
  let sql = "select id
from posts
where user_id in (" <> ids_slice <> ")"
  #(sql, list.flatten([list.map(ids, ParamInt)]), posts_by_ids_decoder())
}

pub fn posts_by_ids_decoder() -> decode.Decoder(PostsByIds) {
  use id <- decode.field(0, decode.int)
  decode.success(PostsByIds(id:))
}

pub type PostsByIdsAndTitle {
  PostsByIdsAndTitle(id: Int)
}

pub fn posts_by_ids_and_title(ids ids: List(Int), title title: String) {
  let ids_slice = string.repeat(",?", list.length(ids))
  let sql = "select id
from posts
where user_id in (" <> ids_slice <> ") and title = ?"
  #(
    sql,
    list.new()
      |> list.append(list.map(ids, ParamInt))
      |> list.append([ParamString(title)]),
    posts_by_ids_and_title_decoder(),
  )
}

pub fn posts_by_ids_and_title_decoder() -> decode.Decoder(PostsByIdsAndTitle) {
  use id <- decode.field(0, decode.int)
  decode.success(PostsByIdsAndTitle(id:))
}

pub type PostsByIdsAndStatus {
  PostsByIdsAndStatus(id: Int)
}

pub fn posts_by_ids_and_status(title title: String, ids ids: List(Int)) {
  let ids_slice = string.repeat(",?", list.length(ids))
  let sql = "select id
from posts
where title = ? and user_id in (" <> ids_slice <> ")"
  #(
    sql,
    list.new()
      |> list.append([ParamString(title)])
      |> list.append(list.map(ids, ParamInt)),
    posts_by_ids_and_status_decoder(),
  )
}

pub fn posts_by_ids_and_status_decoder() -> decode.Decoder(PostsByIdsAndStatus) {
  use id <- decode.field(0, decode.int)
  decode.success(PostsByIdsAndStatus(id:))
}

pub type MultipleSlices {
  MultipleSlices(id: Int)
}

pub fn multiple_slices(titles titles: List(String), ids ids: List(Int)) {
  let titles_slice = string.repeat(",?", list.length(titles))
  let ids_slice = string.repeat(",?", list.length(ids))
  let sql = "select id
from posts
where title in (" <> titles_slice <> ") and user_id in (" <> ids_slice <> ")"
  #(
    sql,
    list.flatten([list.map(titles, ParamString), list.map(ids, ParamInt)]),
    multiple_slices_decoder(),
  )
}

pub fn multiple_slices_decoder() -> decode.Decoder(MultipleSlices) {
  use id <- decode.field(0, decode.int)
  decode.success(MultipleSlices(id:))
}

pub type MultipleSlicesAndArgument {
  MultipleSlicesAndArgument(id: Int)
}

pub fn multiple_slices_and_argument(
  user_id user_id: Int,
  titles titles: List(String),
  ids ids: List(Int),
) {
  let titles_slice = string.repeat(",?", list.length(titles))
  let ids_slice = string.repeat(",?", list.length(ids))
  let sql = "select id
from posts
where user_id = ? and title in (" <> titles_slice <> ") and user_id in (" <> ids_slice <> ")"
  #(
    sql,
    list.new()
      |> list.append([ParamInt(user_id)])
      |> list.append(list.map(titles, ParamString))
      |> list.append(list.map(ids, ParamInt)),
    multiple_slices_and_argument_decoder(),
  )
}

pub fn multiple_slices_and_argument_decoder() -> decode.Decoder(
  MultipleSlicesAndArgument,
) {
  use id <- decode.field(0, decode.int)
  decode.success(MultipleSlicesAndArgument(id:))
}
