
export DATABASE_URL := "mysql://root:daniel@127.0.0.1:3309/parrot"

run:
  gleam run

test:
  #!/bin/bash
  rm -f src/app/sql.gleam
  ../../bin/mysql.sh
  ./priv/reset.sh

  gleam run -m parrot

  tmp_file=$(mktemp /tmp/gleam_test.XXXXXX)
  gleam run > "$tmp_file" 2>&1

  if grep -q "error" "$tmp_file"; then
    echo "❌ FAILED"
    cat "$tmp_file"
  else
    echo "✅ PASSED"
  fi

  rm $tmp_file
