SQLITE_FILE := "file.db"

run:
  gleam run

test:
  #!/bin/bash
  rm -f src/app/sql.gleam
  rm -f {{SQLITE_FILE}}
  sqlite3 {{SQLITE_FILE}} < ./priv/schema.sql
  sqlite3 {{SQLITE_FILE}} < ./priv/seed.sql

  gleam run -m parrot -- --sqlite {{SQLITE_FILE}}

  tmp_file=$(mktemp /tmp/gleam_test.XXXXXX)
  gleam run > "$tmp_file" 2>&1

  if grep -q "error" "$tmp_file"; then
    echo "❌ FAILED"
    cat "$tmp_file"
  else
    echo "✅ PASSED"
  fi

  rm $tmp_file
