import gleeunit/should
import sqlc_gen_gleam/codegen

pub fn comment_dont_edit_test() {
  codegen.comment_dont_edit()
  |> should.equal(
    "//// Code generated by sqlc_gen_gleam. DO NOT EDIT.\n//// versions:\n////   sqlc_gen_gleam v0.0.1\n////",
  )
}
