
export DATABASE_URL := "postgresql://daniel:parrot@127.0.0.1:5432/parrot"

test:
  #!/bin/bash
  rm -f src/app/sql.gleam
  ../../bin/psql.sh
  ./priv/reset.sh

  gleam run -m parrot

  tmp_file=$(mktemp /tmp/gleam_test.XXXXXX)
  gleam run > "$tmp_file" 2>&1

  if grep -q "error" "$tmp_file"; then
    echo "❌ FAILED"
    cat "$tmp_file"
  else
    echo "✅ PASSED"
  fi

  rm $tmp_file
