name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        erlang: ["27"]
        postgres: ["postgres:16", "postgres:17"]

    env:
      DATABASE_URL: postgres://parrot_test:postgres_password@localhost:5432/parrot_test

    services:
      postgres:
        image: ${{ matrix.postgres }}
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_USER: postgres_test
          POSTGRES_DB: parrot_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: ./integration_test
      - run: gleam format --check src test
