name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  integration-sqlite:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install SQLite
        run: sudo apt-get update && sudo apt-get install -y sqlite3
      - name: Run SQLite Integration Tests
        working-directory: integration/sqlite
        run: |
          rm -f src/app/sql.gleam
          rm -f file.db
          sqlite3 file.db < ./priv/schema.sql
          sqlite3 file.db < ./priv/seed.sql
          gleam run -m parrot -- --sqlite file.db
          gleam run

  integration-mysql:
    runs-on: ubuntu-latest
    needs: test
    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: daniel
          MYSQL_DATABASE: parrot
        ports:
          - 3309:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Run MySQL Integration Tests
        working-directory: integration/mysql
        env:
          DATABASE_URL: mysql://root:daniel@127.0.0.1:3309/parrot
        run: |
          rm -f src/app/sql.gleam
          ./priv/reset.sh
          gleam run -m parrot
          gleam run

  integration-psql:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        postgres: ["postgres:16", "postgres:17"]
    services:
      postgres:
        image: ${{ matrix.postgres }}
        env:
          POSTGRES_USER: daniel
          POSTGRES_PASSWORD: parrot
          POSTGRES_DB: parrot
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql postgresql-client
      - name: Run PostgreSQL Integration Tests
        working-directory: integration/psql
        env:
          DATABASE_URL: postgresql://daniel:parrot@127.0.0.1:5432/parrot
        run: |
          rm -f src/app/sql.gleam
          ./priv/reset.sh
          gleam run -m parrot
          gleam run
