name: ci
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam format --check src test

  integration-sqlite:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install SQLite
        run: sudo apt-get update && sudo apt-get install -y sqlite3
      - name: Run SQLite Integration Tests
        working-directory: integration/sqlite
        run: |
          rm -f src/app/sql.gleam
          rm -f file.db
          sqlite3 file.db < ./priv/schema.sql
          sqlite3 file.db < ./priv/seed.sql
          gleam run -m parrot -- --sqlite file.db
          gleam run

  integration-mysql:
    runs-on: ubuntu-latest
    needs: test
    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: daniel
          MYSQL_DATABASE: parrot
        ports:
          - 3309:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Run MySQL Integration Tests
        working-directory: integration/mysql
        env:
          DATABASE_URL: mysql://root:daniel@127.0.0.1:3309/parrot
        run: |
          rm -f src/app/sql.gleam
          ./priv/reset.sh
          gleam run -m parrot
          gleam run

  integration-psql-16:
    runs-on: ubuntu-latest
    needs: test
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: daniel
          POSTGRES_PASSWORD: parrot
          POSTGRES_DB: parrot
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install PostgreSQL 16 Client
        run: |
          # Add PostgreSQL apt repository
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update

          # Install PostgreSQL 16 client tools
          sudo apt-get install -y postgresql-16 postgresql-client-16
      - name: Run PostgreSQL Integration Tests
        working-directory: integration/psql
        env:
          DATABASE_URL: postgresql://daniel:parrot@127.0.0.1:5432/parrot
          PGBIN: /usr/lib/postgresql/16/bin
        run: |
          # Ensure PostgreSQL 16 binaries are used
          export PATH="${PGBIN}:$PATH"

          # Verify correct pg_dump version
          ${PGBIN}/pg_dump --version

          rm -f src/app/sql.gleam
          ./priv/reset.sh
          gleam run -m parrot
          gleam run

  integration-psql-17:
    runs-on: ubuntu-latest
    needs: test
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: daniel
          POSTGRES_PASSWORD: parrot
          POSTGRES_DB: parrot
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install PostgreSQL 17 Client
        run: |
          # Add PostgreSQL apt repository
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update

          # Install PostgreSQL 17 client tools
          sudo apt-get install -y postgresql-17 postgresql-client-17
      - name: Run PostgreSQL Integration Tests
        working-directory: integration/psql
        env:
          DATABASE_URL: postgresql://daniel:parrot@127.0.0.1:5432/parrot
          PGBIN: /usr/lib/postgresql/17/bin
        run: |
          # Ensure PostgreSQL 17 binaries are used
          export PATH="${PGBIN}:$PATH"

          # Verify correct pg_dump version
          ${PGBIN}/pg_dump --version

          rm -f src/app/sql.gleam
          ./priv/reset.sh
          gleam run -m parrot
          gleam run
