name: Update sqlc_version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-sqlc-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest sqlc version
        id: get_version
        run: |
          latest=$(curl -s https://api.github.com/repos/sqlc-dev/sqlc/releases/latest | jq -r .tag_name | sed 's/^v//')
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Get current sqlc_version
        id: get_old_version
        run: |
          old=$(awk -F'"' '/const sqlc_version/ {print $2}' src/parrot/internal/sqlc.gleam)
          echo "old=$old" >> $GITHUB_OUTPUT

      - name: Update sqlc_version in src/parrot/internal/sqlc.gleam
        if: ${{ steps.get_version.outputs.latest != steps.get_old_version.outputs.old }}
        run: |
          new="${{ steps.get_version.outputs.latest }}"
          sed -i.bak -E "s/(const sqlc_version = \")[0-9.]+\"/\1$new\"/" src/parrot/internal/sqlc.gleam
          rm src/parrot/internal/sqlc.gleam.bak

      - name: Create Pull Request
        if: ${{ steps.get_version.outputs.latest != steps.get_old_version.outputs.old }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update sqlc_version to ${{ steps.get_version.outputs.latest }}"
          branch: update-sqlc-version-${{ steps.get_version.outputs.latest }}
          title: "chore: update sqlc_version to ${{ steps.get_version.outputs.latest }}"
          body: "Automated update of sqlc_version to ${{ steps.get_version.outputs.latest }}"
