name: Update sqlc_version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-sqlc-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest sqlc version
        id: get_version
        run: |
          response=$(curl -s https://api.github.com/repos/sqlc-dev/sqlc/releases/latest)
          tag=$(echo "$response" | jq -r .tag_name)
          if [[ -z "$tag" || "$tag" == "null" ]]; then
            echo "Error: Failed to get valid tag name from GitHub API"
            echo "$response" | jq .
            exit 1
          fi
          latest=$(echo "$tag" | sed 's/^v//')
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Get current sqlc_version
        id: get_old_version
        run: |
          old=$(grep "const sqlc_version" src/parrot/internal/sqlc.gleam | awk -F'"' '{print $2}')
          if [[ -z "$old" ]]; then
            echo "Error: Failed to extract current sqlc_version from src/parrot/internal/sqlc.gleam"
            exit 1
          fi
          echo "old=$old" >> $GITHUB_OUTPUT

      - name: Update sqlc_version in src/parrot/internal/sqlc.gleam
        if: ${{ steps.get_version.outputs.latest != steps.get_old_version.outputs.old }}
        run: |
          new="${{ steps.get_version.outputs.latest }}"
          if [[ -z "$new" || "$new" == "null" ]]; then
            echo "Error: New version is empty or null"
            exit 1
          fi
          sed -i.bak -E "s/(const sqlc_version = \")[^\"]+\"/\1$new\"/" src/parrot/internal/sqlc.gleam
          rm src/parrot/internal/sqlc.gleam.bak
          # Verify the update was successful
          updated_version=$(grep "const sqlc_version" src/parrot/internal/sqlc.gleam | awk -F'"' '{print $2}')
          if [[ "$updated_version" != "$new" ]]; then
            echo "Error: Failed to update sqlc_version in the file"
            echo "Expected: $new, Found: $updated_version"
            exit 1
          fi

      - name: Create Pull Request
        if: ${{ steps.get_version.outputs.latest != steps.get_old_version.outputs.old }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update sqlc_version to ${{ steps.get_version.outputs.latest }}"
          branch: update-sqlc-version-${{ steps.get_version.outputs.latest }}
          title: "chore: update sqlc_version to ${{ steps.get_version.outputs.latest }}"
          body: "Automated update of sqlc_version to ${{ steps.get_version.outputs.latest }}"
